apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "db-backup.fullname" . }}
  labels:
    {{- include "db-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.job.schedule | default "0 0,12 * * *" | quote }}
  successfulJobsHistoryLimit: {{.Values.backup.job.successfulJobsHistoryLimit | default 5 }}
  failedJobsHistoryLimit: {{ .Values.backup.job.failedJobsHistoryLimit | default 2 }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: {{ .Values.backup.job.restartPolicy | default "OnFailure" }}
          containers:
          - name: app
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: TZ
              value: {{ .Values.backup.container.timezone | default "Europe/Vienna" }}
            - name: DBS_TO_DUMP
              value: {{ .Values.backup.db_settings.mariadb_mysql.databases_to_dump | quote }}
            - name: DB_HOST
              value: {{ .Values.backup.db_settings.mariadb_mysql.database_host | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.usernameKey | default "db_auth_username" }}
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.passwordKey | default "db_auth_password" }}
            {{- if .Values.backup.mail_settings.enable }}
            - name: ENABLE_SMTP
              value: {{ .Values.backup.mail_settings.enable | quote }}
            - name: SMTP_HOST
              value: {{ .Values.backup.mail_settings.host_setting.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.backup.mail_settings.host_setting.port | quote }}
            - name: SMTP_TLS
              {{- if .Values.backup.mail_settings.auth.tls_encryption }}
              value: "yes"
              {{- else }}
              value: "no"
              {{- end }}
            - name: SMTP_STARTTLS
              {{- if .Values.backup.mail_settings.auth.starttls_encryption }}
              value: "yes"
              {{- else }}
              value: "no"
              {{- end }}
            - name: SMTP_LOGIN_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.mail_settings.auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.mail_settings.auth.existingSecret.usernameKey | default "db_backup_smtp_username" }}
            - name: SMTP_LOGIN_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.mail_settings.auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.mail_settings.auth.existingSecret.passwordKey | default "db_backup_smtp_password" }}
            - name: MAIL_FROM_EMAIL
              value: {{ .Values.backup.mail_settings.mail_details.mail_from_email | quote }}
            - name: MAIL_FROM_NAME
              value: {{ .Values.backup.mail_settings.mail_details.mail_from | quote }}
            - name: RCPT_LIST
              value: {{ .Values.backup.mail_settings.mail_details.mail_recepient_list | quote }} 
            {{- end }}
            {{- if .Values.backup.webdav.enabled }}
            - name: DAVBACKUPENABLED
              value: {{ .Values.backup.webdav.enabled | quote }}
            - name: DAVROOTDIR
              value: {{ .Values.backup.webdav.webdav_root | quote }}
            - name: DAVBACKUPSUBDIR
              value: {{ .Values.backup.webdav.subdirectory | quote }}
            - name: DAVUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.webdav.auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.webdav.auth.existingSecret.usernameKey | default "webdav_username" }}
            - name: DAVPWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.webdav.auth.existingSecret.secretName | default (printf "%s-%s" .Release.Name "secrets") }}
                  key: {{ .Values.backup.webdav.auth.existingSecret.passwordKey | default "webdav_password" }}
            {{- end }}
            - name: PVBACKUPENABLED
              value: {{ .Values.backup.persistent_volume.enabled | quote }}
            - name: NFSBACKUPENABLED
              value: {{ .Values.backup.nfs.enabled | quote }}
            volumeMounts:
            {{- if .Values.backup.persistent_volume.enabled }}
            - mountPath: /mnt/pv-backup
              name: pv-backup
            {{- end }}
            {{- if .Values.backup.nfs.enabled }}
            - mountPath: /mnt/nfs-backup
              name: nfs-backup
            {{- end }}
          volumes:
          {{- if .Values.backup.persistent_volume.enabled }}
          - name: pv-backup
            persistentVolumeClaim:
              claimName: {{- if .Values.backup.persistent_volume.existingClaim }}{{ .Values.backup.persistent_volume.existingClaim }}{{- end }}
          {{- end }}
          {{- if .Values.backup.nfs.enabled }}
          - name: nfs-backup
            nfs:
              server: {{ .Values.backup.nfs.nfs_host }}
              path: {{ .Values.backup.nfs.nfs_path }}
          {{- end }}