{{- if or (not .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.enabled) (not .Values.backup.mail_settings.auth.existingSecret.enabled) (not .Values.backup.webdav.auth.existingSecret.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "secrets" }}
  labels:
    app.kubernetes.io/name: {{ include "db-backup.name" . }}
    helm.sh/chart: {{ include "db-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not .Values.backup.db_settings.mariadb_mysql.database_auth.existingSecret.enabled }}
  db_auth_username: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.user | b64enc | quote }}
  db_auth_password: {{ .Values.backup.db_settings.mariadb_mysql.database_auth.password | b64enc | quote }}
  {{- end }}

  {{- if and .Values.backup.mail_settings.auth.enabled (not .Values.backup.mail_settings.auth.existingSecret) }}
  db_backup_smtp_username: {{ .Values.backup.mail_settings.auth.username | b64enc | quote }}
  db_backup_smtp_password: {{ .Values.backup.mail_settings.auth.password | b64enc | quote }}
  {{- end }}

  {{- if and .Values.backup.webdav.enabled (not .Values.backup.webdav.auth.existingSecret.enabled) }}
  webdav_username: {{ .Values.backup.webdav.auth.webdav_user | b64enc | quote }}
  webdav_password: {{ .Values.backup.webdav.auth.webdav_user_password | b64enc | quote }}
  {{- end }}
{{- end -}}