apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typemill-app-pv
  namespace: chia-manager-docs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi