apiVersion: v2
name: cmsms
description: CMS Made Simple. An easy to use CMS System.
annotations:
  category: CMS
  #ref: https://blog.artifacthub.io/blog/changelogs/
  artifacthub.io/changes: |
    - kind: added
      description: Modules custom folder now symlinked from uploads folder.
    - kind: changed
      description: This chart now actively working with different tags.
    - kind: added
      description: Artifact hub changelog added.
    - kind: fixed
      description: Bug fix copying files init script. Added maxdepth.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.4
#version: 0.1.31-dev

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.2.16"

icon: https://framalibre.org/sites/default/files/leslogos/cmsms_logo.png

home: https://www.cmsmadesimple.org/

maintainers:
  - name: CMS Made Simple Foundation
    url: https://www.cmsmadesimple.org/

sources:
  - https://github.com/OLED1/oleds-helm-charts/tree/main/development/cmsms/cmsms-app-src

dependencies:
- name: mariadb
  version: 11.0.*
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
