apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cmsms.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "cmsms.name" . }}
    helm.sh/chart: {{ include "cmsms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.php: |-
    <?php
      # CMS Made Simple Configuration File
      # Documentation: https://docs.cmsmadesimple.org/configuration/config-file/config-reference
      #
      $config['dbms'] = 'mysqli';
      $config['db_hostname'] = getenv("CMSMS_DB_HOST");
      $config['db_username'] = getenv("CMSMS_DB_USER");
      $config['db_password'] = getenv("CMSMS_DB_USER_PW");
      $config['db_name'] = getenv("CMSMS_DB");
      $config['db_prefix'] = getenv("CMSMS_DB_PREFIX");
      $config['root_url'] = getenv("CMSMS_DOMAIN");
      $config['timezone'] = {{ .Values.cmsms_settings.app_config.timezone | quote }};
      $config['url_rewriting'] = 'mod_rewrite';

    {{- range $value := .Values.cmsms_settings.app_config.additional_config_settings }}
      {{ $value }} 
    {{- end }}
    ?>