{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled }}
{{- if not .Values.externalDatabase.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
    app.kubernetes.io/name: {{ include "cmsms.name" . }}
    helm.sh/chart: {{ include "cmsms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.externalDatabase.enabled }}
  db-username: {{ default "cmsms" .Values.externalDatabase.user | b64enc | quote }}
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  db-username: {{ default "cmsms" .Values.mariadb.auth.username | b64enc | quote }}
  db-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}