{{- if or (not .Values.cmsms_settings.initial_user.existingSecret.enabled) (not .Values.cmsms_settings.setup_smtp.existingSecret.enabled) }}
{{- if or .Values.cmsms_settings.initial_user.create .Values.cmsms_settings.setup_smtp.preconfigure_smtp -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "secrets" }}
  labels:
    app.kubernetes.io/name: {{ include "cmsms.name" . }}
    helm.sh/chart: {{ include "cmsms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if and (not .Values.cmsms_settings.initial_user.existingSecret.enabled) .Values.cmsms_settings.initial_user.create }}
  cmsms_username: {{ default "cmsms" .Values.cmsms_settings.initial_user.username | b64enc | quote }}
  {{- if .Values.cmsms_settings.initial_user.password }}
  cmsms_password: {{ .Values.cmsms_settings.initial_user.password | b64enc | quote }}
  {{- else }}
  cmsms_password: {{ randAlphaNum 25 | b64enc | quote }}
  {{- end }}
  cmsms_email: {{ default "admin@example.com" .Values.cmsms_settings.initial_user.email | b64enc | quote }}
  {{- end }}

  {{- if and .Values.cmsms_settings.setup_smtp.preconfigure_smtp .Values.cmsms_settings.setup_smtp.smtp_auth.auth_needed (not .Values.cmsms_settings.setup_smtp.smtp_auth.existingSecret.enabled) }}
  cmsms_smtp_username: {{ default "cmsms_smtp" .Values.cmsms_settings.setup_smtp.smtp_auth.auth_user | b64enc | quote }}
  cmsms_smtp_password: {{ default "changeme!" .Values.cmsms_settings.setup_smtp.smtp_auth.auth_pw | b64enc | quote }}
  {{- end }}

{{- end }}
{{- end }}