{{- if or (not .Values.cmsms_settings.initial_user.existing_secret.enabled) (not .Values.cmsms_settings.setup_smtp.existing_secret.enabled) (not .Values.cmsms_db.mysql_auth.existing_secret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cmsms.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "cmsms.name" . }}
    helm.sh/chart: {{ include "cmsms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if and (not .Values.cmsms_settings.initial_user.existing_secret.enabled) .Values.cmsms_settings.initial_user.create }}
  cmsms_username: {{ default "cmsms" .Values.cmsms_settings.initial_user.username | b64enc | quote }}
  {{- if .Values.cmsms_settings.initial_user.password }}
  cmsms_password: {{ .Values.cmsms_settings.initial_user.password | b64enc | quote }}
  {{- else }}
  cmsms_password: {{ randAlphaNum 25 | b64enc | quote }}
  {{- end }}
  cmsms_e-mail: {{ .Values.cmsms_settings.initial_user.email | b64enc | quote }}
  {{- end }}
{{- end }}