apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmsms.fullname" . }}-app
  labels:
    {{- include "cmsms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cmsms_app.service.type }}
  ports:
    - port: {{ .Values.cmsms_app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cmsms.selectorLabels" . | nindent 4 }}
---
{{- if and (not .Values.cmsms_db.external_db.enabled) .Values.cmsms_db.internal_db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmsms.fullname" . }}-mysql-db
  labels:
    {{- include "cmsms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cmsms_db.internal_db.service.type }}
  ports:
    - port: {{ .Values.cmsms_db.internal_db.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cmsms.selectorLabels" . | nindent 4 }}
{{- end }}