apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typemill.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "typemill.name" . }}
    helm.sh/chart: {{ include "typemill.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
    {{- include "typemill.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "typemill.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "typemill.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "typemill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.typemill.containerPort | default "80" }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /tm/login
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.typemill.host | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /tm/login
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.typemill.host | quote }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          startupProbe:
            httpGet:
              path: /tm/login
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.typemill.host | quote }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: typemill-data
            mountPath: /var/www/html/settings
            subPath: settings
          - name: typemill-data
            mountPath: /var/www/html/content
            subPath: content
          - name: typemill-data
            mountPath: /var/www/html/media
            subPath: media
          - name: typemill-data
            mountPath: /var/www/html/plugins
            subPath: plugins
          - name: typemill-data
            mountPath: /var/www/html/themes
            subPath: themes
          {{- end }}
          {{- if .Values.typemill.htaccess }}
          - name: typemill-htaccess
            mountPath: /var/www/html/.htaccess
            subPath: .htaccess
          {{- end }}
      {{- if .Values.persistence.enabled }}
      initContainers:
      - name: install-update-typemill-plugins
        image: busybox:latest
        command: ['sh', '-c', 'sh /mnt/install-selected-plugins.sh']
        volumeMounts:
        - name: typemill-data
          mountPath: /mnt/typemill_plugins/
          subPath: plugins
        - name: plugin-install-routine
          mountPath: /mnt/install-selected-plugins.sh
          subPath: install-selected-plugins.sh
      {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: typemill-data
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "typemill.fullname" . }}-typemill-data{{- end }}
      {{- end }}
      - name: typemill-htaccess
        configMap:
          name: {{ template "typemill.fullname" . }}-htaccess
      - name: plugin-install-routine
        configMap:
          name: {{ template "typemill.fullname" . }}-plugin-install-routine
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
