apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typemill.fullname" . }}
  labels:
    {{- include "typemill.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "typemill.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "typemill.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "typemill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.persistence.enabled }}
          volumeMounts:
          - name: typemill-data
            mountPath: /var/www/html/settings
            subPath: settings
          - name: typemill-data
            mountPath: /var/www/html/content
            subPath: content
          - name: typemill-data
            mountPath: /var/www/html/media
            subPath: media
          - name: htaccess
            mountPath: /var/www/html/.htaccess
            subPath: .htaccess
          {{- else }}
          volumeMounts:
          - name: htaccess
            mountPath: /var/www/html/.htaccess
            subPath: .htaccess
          {{- end }}

      volumes:
      {{- if .Values.persistence.enabled }}
      - name: typemill-data
        persistentVolumeClaim:
          claimName: typemill-app-pv
      {{- end }}
      - name: htaccess
        configMap:
          name: typemill-htaccess
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
